# Setup
title: Blog
description: what if I can right my wrongs and save you from the pains?
url: https://usigned.github.io
avatar: /myAvatar.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
 username: qing
 card: summary
logo: logo.png
social:
  name: Zhengqing Lin
  links:
    - https://twitter.com/usigned
    - https://github.com/usigned
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: '4720e5f821d1d1e1c627'    #生成的clientID
  clientSecret: 'de44c48519dd5ea5b88f7b73a15167f15235536a'   #同上
  repo: Usigned.github.io    #仓库名称
  owner: Usigned    #github用户名
  admin: Usigned

# Specify the author for blog posts
author:
  name: Usigend
  url: https://github.com/usigned/
  email: aloha-qing@qq.com
